version: '3'

services:
  nginx:
    image: 'nginx:stable'
    volumes:
      - ./work.conf:/etc/nginx/conf.d/work.conf
      - ./:/app
    ports:
      - '1234:8080'
  php:
    build: .
    volumes:
      - ./:/app
  postgres:
    image: 'postgres:9.6.24-bullseye'
    environment:
      POSTGRES_PASSWORD: "example"
    volumes:
      - ./storage:/app
    working_dir: /app
    ports:
      - "5432:5432"